# Сортировка

На собеседовании я не справился с сортировкой элементов массива. Поэтому я посчитал, что необходимо немедленно восполнить этот пробел.

Итак, выполним задачу сортировки, в которой требуется так разместить элементы массива, чтобы каждый элемент был меньше или равен следующему за ним.

In [1]:
# Сначала создадим массив, который будем отсортировывать. Пусть он состоит из 100 целочисленных значений.
import numpy as np
A = np.random.randint(100, size=100)
B, C, D = A, A, A
A

array([25, 39, 48, 93, 69, 41, 79, 84, 40, 23, 10, 10, 35, 73, 74, 85, 54,
       75, 37,  5, 90, 96, 58, 59,  0, 94, 58, 34, 70, 78, 89, 55, 94, 48,
        3, 67, 90, 52, 29, 88, 20, 37, 82, 16, 48, 37,  5, 92, 76, 43, 62,
       83, 37, 71, 36, 53, 72, 32,  8, 58, 77, 37, 61, 97, 52, 35, 22, 97,
       59, 58, 20, 17, 24, 55, 70, 18,  6, 20, 91, 13, 96, 74, 84, 38, 45,
       13, 33, 76, 76, 87, 12, 56, 75, 42, 54,  9, 96, 31, 69, 86])

In [2]:
# Применим алгоритм сортировки выбором (Selection Sort)
# NB: индексация идёт с 0

def selectionSort(arr):
    for i in range(len(arr)): # Для i = по длинне массива (от 0 до n)
        smallest = i # установим значение переменной smallest равным i
        for j in range(i+1, len(arr)): # Для j = i+1 до n
            if arr[j] < arr[smallest]: # Если эл. j меньше эл. smallest
                smallest = j # присваиваем переменной smallest значение j
     
        arr[i], arr[smallest] = arr[smallest], arr[i] # обменять значения элементов массива

In [3]:
%time # Оценим время выполенения
selectionSort(B)
B

CPU times: user 7 µs, sys: 2 µs, total: 9 µs
Wall time: 18.8 µs


array([ 0,  3,  5,  5,  6,  8,  9, 10, 10, 12, 13, 13, 16, 17, 18, 20, 20,
       20, 22, 23, 24, 25, 29, 31, 32, 33, 34, 35, 35, 36, 37, 37, 37, 37,
       37, 38, 39, 40, 41, 42, 43, 45, 48, 48, 48, 52, 52, 53, 54, 54, 55,
       55, 56, 58, 58, 58, 58, 59, 59, 61, 62, 67, 69, 69, 70, 70, 71, 72,
       73, 74, 74, 75, 75, 76, 76, 76, 77, 78, 79, 82, 83, 84, 84, 85, 86,
       87, 88, 89, 90, 90, 91, 92, 93, 94, 94, 96, 96, 96, 97, 97])

In [4]:
# Теперь применим алгоритм сортировки вставкой (Insertion Sort)

def insertionSort(arr):
 
    for i in range(1, len(arr)): # Для i = 1 до n
 
        key = arr[i] # присвоим key значение i-го элемента
 
        j = i-1 # присвоим j значение i-1
        while j >=0 and arr[j] > key: # Пока j >=0 и arr[j] > key
                arr[j+1] = arr[j] # Присвоить arr[j+1] значение arr[j]
                j -= 1 # уменьшить j на единицу
        arr[j+1] = key # перенесем элемент изначально находившийся в arr[i] на новую позицию

In [5]:
%time
insertionSort(C)
C

CPU times: user 7 µs, sys: 2 µs, total: 9 µs
Wall time: 18.1 µs


array([ 0,  3,  5,  5,  6,  8,  9, 10, 10, 12, 13, 13, 16, 17, 18, 20, 20,
       20, 22, 23, 24, 25, 29, 31, 32, 33, 34, 35, 35, 36, 37, 37, 37, 37,
       37, 38, 39, 40, 41, 42, 43, 45, 48, 48, 48, 52, 52, 53, 54, 54, 55,
       55, 56, 58, 58, 58, 58, 59, 59, 61, 62, 67, 69, 69, 70, 70, 71, 72,
       73, 74, 74, 75, 75, 76, 76, 76, 77, 78, 79, 82, 83, 84, 84, 85, 86,
       87, 88, 89, 90, 90, 91, 92, 93, 94, 94, 96, 96, 96, 97, 97])

# Сортировки при RAM < размер массива

__Внешняя сортировка__ — сортировка данных, расположенных на периферийных устройствах и не вмещающихся в оперативную память, то есть когда применить одну из внутренних сортировок невозможно.

Используем алгоритм сортировки слиянием.

In [6]:
# определим функцию merge(массив, начальный, стержневой, конечный индексы),
# которая объединяет массив из двух подмассивов

def merge(arr, l, m, r):
    n1 = m - l + 1
    n2 = r- m
 
    # создадим временные массивы
    L = [0] * (n1)
    R = [0] * (n2)
 
    for i in range(0 , n1):
        L[i] = arr[l + i]
 
    for j in range(0 , n2):
        R[j] = arr[m + 1 + j]
 
    # сольем подмассивы в единый
    i = 0     # первый индекс первого подмассива
    j = 0     # первый индекс второго подмассива
    k = l     # первый индекс объединенного подмассива
 
    while i < n1 and j < n2 :
        if L[i] <= R[j]:
            arr[k] = L[i]
            i += 1
        else:
            arr[k] = R[j]
            j += 1
        k += 1
 

    while i < n1:
        arr[k] = L[i]
        i += 1
        k += 1
 

    while j < n2:
        arr[k] = R[j]
        j += 1
        k += 1

        
# определим функцию mergeSort(массив, начальный, конечный индексы)

def mergeSort(arr,l,r):
    if l < r:
 
        # "Разделяй" - разделяем arr путем нахождения стержневого индекса
        m = (l+(r-1))/2
 
        # "Властвуй" - рекурсивно сортируем элементы в каждой половине,
        # созданной на этапе "Разделяй"
        mergeSort(arr, l, m)
        mergeSort(arr, m+1, r)
        merge(arr, l, m, r)

In [7]:
n = len(D)
mergeSort(D,0,n-1)
D

array([ 0,  3,  5,  5,  6,  8,  9, 10, 10, 12, 13, 13, 16, 17, 18, 20, 20,
       20, 22, 23, 24, 25, 29, 31, 32, 33, 34, 35, 35, 36, 37, 37, 37, 37,
       37, 38, 39, 40, 41, 42, 43, 45, 48, 48, 48, 52, 52, 53, 54, 54, 55,
       55, 56, 58, 58, 58, 58, 59, 59, 61, 62, 67, 69, 69, 70, 70, 71, 72,
       73, 74, 74, 75, 75, 76, 76, 76, 77, 78, 79, 82, 83, 84, 84, 85, 86,
       87, 88, 89, 90, 90, 91, 92, 93, 94, 94, 96, 96, 96, 97, 97])

Использованная литература: _Кормен, Т._ __Алгоритмы: вводный курс.__ - М., 2016.